[tox]
envlist =
    {py314,py313,py312}
    coverage

[testenv]
extras = dev
setenv =
    TESTPATH=tests/
    RCFILE=setup.cfg
commands =
    python -m coverage run --rcfile={env:RCFILE} --source=schwab -p -m pytest -W ignore::urllib3.exceptions.SystemTimeWarning -W ignore::urllib3.exceptions.InsecureRequestWarning {env:TESTPATH}

[testenv:coverage]
skip_install = true
deps = coverage
commands =
    python -m coverage combine
    python -m coverage report
    python -m coverage html
